# Generated by Django 3.1.1 on 2021-05-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfrstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='nivel',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='url_proyecto',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
