# Generated by Django 3.1.1 on 2021-05-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfrstapp', '0003_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tipo',
        ),
    ]
