# Generated by Django 3.1.1 on 2021-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfrstapp', '0006_auto_20210524_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='abstraccion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='categorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='condicionales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='control_flujo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='interactividad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='nombre_proyecto',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectos',
            name='paralelismo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='sincronizacion',
            field=models.IntegerField(default=0),
        ),
    ]
