# Generated by Django 3.1.1 on 2021-05-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfrstapp', '0008_auto_20210527_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='url_proyecto',
            field=models.CharField(max_length=100),
        ),
    ]
