# Generated by Django 3.1.1 on 2021-05-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfrstapp', '0009_auto_20210527_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='nombre_zip',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
