# Generated by Django 3.1.1 on 2021-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfrstapp', '0010_proyectos_nombre_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='nombre_zip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
