# Generated by Django 3.1.1 on 2021-05-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfrstapp', '0012_remove_proyectos_nombre_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='name_proyecto',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
