# Generated by Django 3.1.1 on 2021-06-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfrstapp', '0013_proyectos_name_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='url_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
